#!/usr/bin/env -S ruby -Ilib
# typed: true
# frozen_string_literal: true

require "minic"

name = T.let(ARGV[0], T.nilable(String))

if name.nil? || name == ""
  puts "Input file is empty! Please provide a file to compile"
  exit(1)
end

body = File.open(name).read
begin
  file = Minic::FileSet::File.new(name:, body:)
  lexer = Minic::Lexer.new(file:)
  parser = Minic::Parser.new(lexer:)
  ast = parser.parse
  Minic::SemanticAnalyzer.new(ast:).check

  out = File.open("./build/program.c", "w")
  Minic::Generator.new(ast:, out:).generate
rescue Minic::Error => e
  puts "---"
  puts "Error: #{e}"
  puts "---"
  exit(1)
end
